// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AvailableLocales() {
  return window['go']['main']['App']['AvailableLocales']();
}

export function CreateInstance(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateInstance'](arg1, arg2, arg3, arg4);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function Direction() {
  return window['go']['main']['App']['Direction']();
}

export function InstanceStatus(arg1) {
  return window['go']['main']['App']['InstanceStatus'](arg1);
}

export function ListInstances() {
  return window['go']['main']['App']['ListInstances']();
}

export function ListVersions() {
  return window['go']['main']['App']['ListVersions']();
}

export function Locale() {
  return window['go']['main']['App']['Locale']();
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StopInstance(arg1) {
  return window['go']['main']['App']['StopInstance'](arg1);
}

export function Strings() {
  return window['go']['main']['App']['Strings']();
}

export function SuggestPort(arg1) {
  return window['go']['main']['App']['SuggestPort'](arg1);
}
