// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function AvailableLocales():Promise<Array<string>>;

export function CreateInstance(arg1:string,arg2:string,arg3:string,arg4:number):Promise<engine.Instance>;

export function DeleteInstance(arg1:string):Promise<void>;

export function Direction():Promise<string>;

export function InstanceStatus(arg1:string):Promise<engine.Status>;

export function ListInstances():Promise<Array<engine.Instance>>;

export function ListVersions():Promise<Array<engine.Version>>;

export function Locale():Promise<string>;

export function StartInstance(arg1:string):Promise<void>;

export function StopInstance(arg1:string):Promise<void>;

export function Strings():Promise<{[key: string]: string}>;

export function SuggestPort(arg1:string):Promise<number>;
